dafny-lang/ide-vscode

- sonar-project.properties
This adds the sonar configuration for the production sonar account.
⚠️ Please wait with merging until the development has moved to this repository!
> Add stable sonar configuration

- CHANGELOG.md
- package.json
- src/stringResources/languageServer.ts
- src/stringResources/messages.ts
- src/ui/providers/statusbarProvider.ts
Adds the verification indicator as requested in #23.
> Verification Indicator

- CHANGELOG.md
- package.json
- src/ideApi/_IdeApi.ts
Group verification errors and their related locations by using the "Related Information" UI for diagnostics.
Related PR in Dafny
https://github.com/dafny-lang/dafny/pull/1327
> Group verification errors and their related locations

- CHANGELOG.md
- src/stringResources/languageServer.ts
- src/stringResources/messages.ts
- src/ui/providers/statusbarProvider.ts
This PR adds support for the status messages introduced with https://github.com/dafny-lang/dafny/pull/1307.
> Update status message handling

- .vscodeignore
- README.md
Resolves #54 
@robin-aws Do you have any further instructions that could be beneficial here?
> Add build instructions to the README

- syntaxes/Dafny.tmLanguage
> Syntax highlight strings

- CHANGELOG.md
- README.md
- src/constants.ts
- syntaxes/Dafny.tmLanguage
This PR intends to prepare everything needed for the release of v2.0.0.
> Prepare v2.0.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/extension.ts
> fix: Resolve Promise.any is not a function error

- .github/workflows/ci.yaml
This PR adapts the GitHub actions to run them upon every pull request.
> Make the build run for pull requests

- CHANGELOG.md
- src/commands.ts
- src/ui/compileCommands.ts
> fix: Open SaveAs for untitled documents

- .eslintrc.json
- src/language/api/compilationStatus.ts
- src/ui/compilationStatusView.ts
- src/ui/messages.ts
This implements a simple mechanism to report plain-text details about the
verification process.
This is the companion PR of https://github.com/dafny-lang/dafny/pull/1655
> feat(notifications): Display verification progress messages, if any

- src/language/api/compilationStatus.ts
- src/ui/compilationStatusView.ts
Fixes #108.
Dafny change: https://github.com/dafny-lang/dafny/pull/1673
> fix: Use VerificationStarted instead of VerificationInProgress

- package.json
> chore: UX for lists edit directly in settings.json

- README.md
Otherwise we have to update it every time we make a new Dafny release
> Remove version number from README

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
Fixes #176, the problem with identifiers starting with "class".
Manual test added.
> Fix syntax highlighting problem

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
> Fix: stop sign for multiline strings

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
Fixes #221 
Verified visually that all tests in the regression test still pass.
> Added variable declaration to avoid mixing types and function call

- package.json
> chore-counterexample

- package.json
Closes https://github.com/dafny-lang/dafny/issues/1797
> Set a default time limit of 20 seconds to avoid long freezes

- src/ui/messages.ts
> chore: Clarify download prompt

- src/test/suite/verificationSymbolStatusView.test.ts
- src/ui/verificationSymbolStatusView.ts
Correctly handle a difference between verifiable symbols and document symbols
Added a unit test
> Correctly handle a difference between verifiable and document symbols

- src/ui/verificationGutterStatusView.ts
Fixes #259 by short-circuiting the line skipping if there are resolution errors.
> Fix disappearing resolution errors with verification tests.

- CHANGELOG.md
- package-lock.json
- package.json
- publish_process.js
> Release v2.8.2

- publish_process.js
This PR fixes publish_process.js by ensuring constant.ts is correctly updated. I tested this PR locally and now it works.
> Fix the Dafny updating mechanism in publish_process.js

- src/ui/compilationStatusView.ts
This was forgotten in the previous PR #342
> Remove the "s" if not plural. Forgot to commit that file

- src/test/verification.test.ts
Add integration test that checks that verification through a solver works
> Add verification integration test

- CHANGELOG.md
- package-lock.json
- package.json
- src/constants.ts
* Update version to 3.0.5
* Use Dafny 3.12
> Release v3.0.5 (updated Dafny to 3.12.0)

- package.json
I suggest the following change to fix #381 and fix #379
> Chore: Better description of automatic verification

- src/ui/verificationSymbolStatusView.ts
- Fix comparison so items in the the UI for verification tests are removed when they're out of date.
- Manually tested that verification tests are now kept up to date
> Fix the removal of verification tests

- package.json
- Let the extension use the Dafny server to track changes in `dfyconfig.toml` files
- Manually assert that changes in `dfyconfig.toml` files are picked up instantly, without saving the file.
- Assert that only opening the `dfyconfig.toml` already publishes diagnotics
> Let the extension use the Dafny server to track changes in the project file

- package-lock.json
- package.json
- src/extension.ts
- src/language/dafnyLanguageClient.ts
The main driver of this update is that it improves error handling. Specifically it will show an error when the LSP connection becomes corrupted.
> Update LSP client to 9.0.0
