dafny-lang/ide-vscode

- CHANGELOG.md
- package.json
- src/ui/providers/statusbarProvider.ts
As requested in #32, this PR changes the verification status to *Not Verified* as soon as a document was changed, independently from the language server.
> Change to "not verified" upon document changes

- CHANGELOG.md
- package.json
- src/constants.ts
- src/language/dafnyLanguageClient.ts
This PR adds VSCode option entries for the following two new language server settings:
- Verification time limit
- Number of virtual cores used by the verification
> Add verification configs

- package-lock.json
- package.json
- tsconfig.json
This PR is a follow-up for issue #80 and PR #81. It updates the `@types/node` package to  `v12.12.70` and downgrades the target library to `ES2019`. With this change, `any` is disclosed as an unknown member of `Promise`.
> fix: Improve typings to better reflect the target environments

- CHANGELOG.md
- syntaxes/Dafny.tmLanguage
Resolves #85 
Furthermore, it mitigates the risk of breaking the syntax highlighting of the whole file if there's anything parsed wrong by terminating strings at the end of the line.
> fix: Fix string highlighting for method arguments

- src/ui/messages.ts
A regular Dafny user pointed out that the compilation message is misleading for several reasons.
Current message:
'$(thumbsup) Compilation succeeded';
Suggested message:
'Resolution succeeded. Awaiting verification...';
Here is why:
- "Compilation" is normally the step that happens after verification. Hence, the current messages would indicate that Dafny files were translated before verification even started, which is not the case. Hence, I use the wording "Resolution" which is consistent with the other message `$(thumbsdown) Resolution Failed';`
- I removed $(thumbsup). Until recently, thumbs up was used only when verification succeeded, which makes sense given its "all right" meaning. Providing an intermediate thumbs up at resolution time feels totally unnecessary and even misleading to …
> Misleading message for compilation fixed

- package.json
- src/constants.ts
- src/language/dafnyLanguageClient.ts
This is the companion PR of https://github.com/dafny-lang/dafny/pull/1654 ; it's intended to let users experiment with caching in VSCode (caching is on by default in Emacs)
> feat(config): Allow users to turn on caching

- src/language/dafnyInstallation.ts
If someone deletes a configured language server runtime or compiler path, there will remain an empty string.
Previously, it would have been interpreted wrongly like a "relative path", and users would have needed to click on the gears icon next to the setting, and click "reset", which is unintuitive, since it was empty when they first edited it.
With this commit, it is correctly interpreted as "switch back to default"
This would have saved me the first time, and I just learned it would have saved someone else from spending a few hours of trouble.
Fixes #105
> Fix empty configuration path that leads to the extension not working

- package-lock.json
- package.json
This PR raises the installed mocha version to 9.2.0 to raise the vulnerable nanoid version from `3.1.25` to `3.1.31`.
See https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
> fix: Update mocha to 9.2.0

- CHANGELOG.md
- src/ui/ghostDiagnosticsView.ts
This PR partially fixes #126 by making the text selection inside ghost statements visible. This is achieved by setting the opacity (hex alpha channel) to 50% of the decorator's background color.
PS: As I cannot unlink issue #126, please reopen it after merging since there is another part to it.
> fix: Make selection inside ghost statements visible

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
Note that the second "id" is no longer understood as a type (previously it was matching ": id" as a type ascription), but now it's understood a function correctly.
Before:
After:
> fix: type ascription should not be applicable to double colon

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
I added more regression tests for highlighting and explained further why we can't turn on recursive parsing in some cases, in case someone things it's a good idea to put it back.
> Added some regression tests for highlighting.

- src/ui/ghostDiagnosticsView.ts
This PR intends to resolve/mitigate #139. However, I couldn't reproduce the issue myself so I can't confirm the fix myself. Moreover, it may improve the mixed experience reported in #126.
Instead of creating a new decoration object with every request, only a single one is created.
> fix: Occasionally missing red squiggles under errors

- src/ui/compilationStatusView.ts
I witnessed that sometimes verification is not canceled in a timely manner, leading to obsolete notifications to be received by the client. This PR ensures that obsolete notifications are not sent if notifications for a newer document is available.
> Fix: Avoid out-of-order messages

- src/language/dafnyInstallation.ts
If the user empties the field "language server path", it should be treated the same as if it was null. It's totally unobvious to have to "reset" this parameter.
Before this PR, a setting like this:
was setting the language server path to "" and since it was non-null, it would not let the extension download Dafny, for example.
> If language server path "" should be the same as null.

- package.json
- src/dotnet.ts
- src/language/dafnyLanguageClient.ts
- src/startupCheck.ts
- src/ui/compileCommands.ts
- src/ui/dafnyVersionView.ts
- src/ui/messages.ts
Fixes #112 
If we specify a directory
If we specify an executable that is not a compatible dotnet file
If we specify a _file_ that is not executable (sic!), at least we don't get the "no compatible dotnet installed", we get an explicit error about what happened
Finally, I changed the default error message from `There is no compatible dotnet runtime installed` to `No compatible dotnet runtime found`, and this message is shown only if the user did not specify an explicit dotnet path.
> Better error if dotnet is not installed or not configured properly

- src/language/dafnyInstallation.ts
I just solved the case of someone with a Mac M1 architecture, brew installed, but VSCode couldn't run it within the Dafny extension.
After finding the Stackoverflow post that solved the problem, I add a link to it for future users.
> Feat: Hint if brew not found.

- src/dotnet.ts
- src/language/dafnyInstallation.ts
Previously, "Make exe" on Mac M1 architectures would be failing silently if java was not present (for the DafnyRuntime dependency)
Now, it raises an explicit error by testing the java version.
> Better error message if java is missing.

- .vscode/launch.json
- package.json
- src/dotnet.ts
- src/language/dafnyInstallation.ts
- src/ui/ghostDiagnosticsView.ts
- Enable starting the extension with a custom language server using an environment variable, which is useful for development scenarios. You can imagine having a make target in the Dafny repository that starts VSCode with the language server from the repository: `DAFNY_LANGUAGE_SERVER=./Binaries/DafnyLanguageServer.dll code`.
- Split the launch configuration "Run Extension" into "Run with default server" and "Run with $DAFNY_LANGUAGE_SERVER"
- Small update to `checkSupportedDotnetVersion` so it's agnostic to symlinks.
Manually tested both features
> Enable configuring a custom language server through an environment variable

- src/language/api/compilationStatus.ts
- src/ui/compilationStatusView.ts
- src/ui/messages.ts
Fixes #174 but will need Dafny Language Server to support those messages afterwards.
Alternative to discuss:
* Should we replace "Parsing started" with "Resolution started" and remove the second "Resolution started" message?
> Added missing status messages.

- src/language/dafnyInstallation.ts
Note that previously, Java recognition is done by testing `stdout`. I know for sure that this doesn't work on my system, as it should test `stderr` instead. However, I also do not know how other systems are. So I conservatively tested both, just to be safe.
Fixes #180, #182
cc: @MikaelMayer and @prvshah51
> Avoid downloading dmg when build from source & fix Java recognition

- package-lock.json
- package.json
- src/commands.ts
- src/extension.ts
- src/language/dafnyInstallation.ts
- src/startupCheck.ts
- src/ui/messages.ts
* When dotnet is not installed or not found, the button meant to open the Dafny setting previously opened the command palette, which was completely pointless. Users would have had to type "Dafny" manually, and then navigate manually to the setting "Dotnet executable path". With this PR, this button now display immediately the option to the absolute path to the dotnet executable so that it can be modified straight away
* When brew fails to install dotnet, the error message is now much more explicit on the resolution steps, which I found consistently worked for mac M1 users.
> Better dotnet and brew error messages

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
The issue is that the syntax highlighter was expecting "var" to be followed by a semicolon ";". If not, it would never exit the fact that it's a "var" declaration and would not highlight anything else.
I added a few keywords and ensured that the type after the var is highlighted as a type as well.
Now:
Fixes #230
> Syntax highlighting after "var" fixed

- package.json
- src/constants.ts
- src/ui/dafnyIntegration.ts
- src/ui/verificationGutterStatusView.ts
- src/ui/verificationSymbolStatusView.ts
Fixes https://github.com/dafny-lang/ide-vscode/issues/237
Fixes https://github.com/dafny-lang/ide-vscode/issues/235
- Add a version check to prevent processing out-of-date symbolStatus updates
- Enable turning verification status in the test panel on/off
If you hold the enter key to continuously insert newlines, the 'play' icon from the verification symbol status still lags behind the moving text. I've tried to find whether it applies outdated data, but everything checks out, so I'm very confused as to while the visuals don't.
> Ensure gutter icons show up in the correct locations

- src/test/suite/verificationSymbolStatusView.test.ts
- src/ui/verificationSymbolStatusView.ts
- Prevent overlap of play and gutter icons on parent nodes such as classes and modules.
- Prevent visible and internal state of testItems from getting out of sync, which could occur when cancelling a run while it was returning results.
Manually tested
> Prevent overlap of play and gutter icons on parent nodes

- package-lock.json
- package.json
- src/language/dafnyInstallation.ts
- src/test/suite/MockingUtils.ts
- src/test/suite/verificationSymbolStatusView.test.ts
- src/ui/verificationGutterStatusView.ts
- src/ui/verificationSymbolStatusView.ts
Previously, in Windows, the LSP's string URI were a bit different than the VSCode's Uri.toString().
Namely, the LSP was retuning:
`file:///c:/...`
whereas `Uri.ToString()` in VSCode was returning
`file:///c%3A/...`
Thus, this PR transforms URI received by the LSP into their canonical form for the Verification Symbol Status view, where the canonical URI is needed because of the event handler `e.document.uri.toString()` in `window.onDidChangeTextDocument`
Second, this PR stores the latest nightly build version so that if the GitHub API rate limit is reached, a client will not revert to the previous stable version.
Third, deactivated two problematic tests that are passing locally but timeout in CI because of seemingly restrictive API quota limits.
> Fix a bug in Windows where the gutter's skipped lines are wrong.

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
This PR fixes #240 by checking that the ":" is not preceeded by "label <ident>", "assert <indent>" and "requires <indent>", so that its right-hand side is not misinterpreted as a type.
> Fix highlighting of labelled statements

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
Change the highlight grammar and added a test to fix #269
Now:
> Fix: Number followed by `<` incorrectly highlighted as a generic

- src/language/dafnyInstallation.ts
We figured out that `brew update` could be a bottleneck for some users so this PR makes it optional
> Fix: Make brew update optional

- CHANGELOG.md
- package-lock.json
- package.json
Making `brew update` optional is critical for some of our users, so I would not delay publishing this update.
> Release v2.8.5

- src/language/dafnyInstallation.ts
- src/ui/dafnyIntegration.ts
- Only build the language server when building Dafny from source for the IDE
- The Dafny language server 3.9 does not require Java to be build, so the Java check can be removed for version 3.9 and up
Ran this on a M1 mac where previously Java could not be found from the VSCode Dafny plugin, and now it built from from source correctly.
> Only require Java to be installed when using a Dafny version before 3.9

- .gitignore
- README.md
- src/language/dafnyInstallation.ts
If `dotnet` is installed
and placed in `dafny.dotnetExecutablePath`
custom source should still be able to be built.
To do this `checkSupportedDotnetVersion`
needs to be the primary way to detect `dotnet`.
This has the side effect of both not double installing from `brew` but also not requireing an install if `dotnet` is already installed.
The `wget` call is also removed
since there are already helpers to perform this get and unzip. They are updated to take a `thing` to facilitate logging. There is also a bit of update to the `Z3` section
to account for this change.
The largest issue with this was
`Source/DafnyCore/DafnyCore.csproj`
has direct `dotnet` build targets.
This means that call to build will fail
if `dotnet` is not on the `PATH`.
This is unfortunate, but…
So we add it for that …
> fix: `dafny.dotnetExecutablePath` works to install custom source

- src/ui/ghostDiagnosticsView.ts
Fixes https://github.com/dafny-lang/dafny/issues/3041
Implemented @keyboardDrummer 's suggestion to re-render on the client on every edit, rather than sending up-to-date diagnostics (even if unchanged)
> Fix: Ghost highlighting no longer out-of-date

- package.json
- src/commands.ts
- src/ui/counterExamplesView.ts
This patch adds a new contextual menu option to allow copying the counterexamples received from the language server to the system clipboard.  At present, non-trivial counterexamples are hard to read in the current "everything appears in one line" form.  Additionally, they are difficult to share with colleagues or instructors, inhibiting "rubber-duck" counterexample debugging.  For instance, I have a counterexample that stretches, I'd wager, _twenty to thirty_ screen widths across in a project I'm working on now - honestly I have no idea how to parse it at that point.
I think all parties agree that #52 would go a long way to addressing the former and, depending on how VS code lets users extract state from the debugger, potentially the latter too.  However, this issue hasn't seen any …
> Allow copying counterexamples to the clipboard

- src/language/dafnyInstallation.ts
This PR ensures that two instances of VSCode can run Dafny on a locally built DafnyLanguageServer.dll without the second crashing like this
VSCode will basically detect a custom installation, and copy all the necessary dependencies to a unique temporary folder. This enables that:
- Developers writing Dafny code can also continuously compile the DLLs without having an error that the DLL are being used, e.g. they can also run tests in their IDE.
- There can be multiple instances of VSCode running.
- Reloading VSCode always copies the files again, so one can simply reload VSCode after compiling the language server.
> Support two instances of VSCode without crashing.

- src/language/dafnyInstallation.ts
- src/test/suite/extension.test.ts
This updates the installation process to always try to download a binary distribution, using the current OS _and_ architecture, and only build from source if the download fails. This should allow us to support other architectures seamlessly in the future (and support the case where, for some reason, we fail to upload a binary for a certain version/OS/arch combination).
> Always attempt to find a binary distribution

- publish_process.js
Requires change after a `package.json` property was renamed from `preferredVersion` to `version`.
> Fix publish script

- src/constants.ts
- src/language/githubReleaseInstaller.ts
Tested twice (to test the installation and the use of an existing installation):
- latest nightly
- latest
- 3.9.1
- custom
- `Ran with $DAFNY_LANGUAGE_SERVER`
> Fix github installer paths

- src/language/fromSourceInstaller.ts
There was a double "Source/" in the custom installation script which is not thoroughly tested.
> Fixed double source

- src/language/dafnyLanguageClient.ts
Introduce a temporary fix so setting verification cores to 0 (the default) doesn't stop verification
> Introduce a temporary fix for verification cores set to 0

- src/language/dafnyLanguageClient.ts
DafnyLanguageServer crashes because the way the number of cores is computed could result in a float number where the server option is expecting an `uint`.
> Cannot parse argument '8.5' for option '--cores' as expected type 'System.Int32'.
> Fix non-integer number of cores.

- src/language/customPathInstaller.ts
- src/test/suite/MockingUtils.ts
- src/test/suite/extension.test.ts
With 3.0.1, the Dlls and executables were no longer copied from a custom installation to the new one. This prevents Dafny developers to compile and then refresh VSCode as it was enabled recently.
This PR fixes that.
> Reinstated the copy of the executable

- src/ui/compilationStatusView.ts
Partially solves the issue #339 
Before when verification finishes on Windows
After this PR when verification finishes on Windows
The reason was that a ":" was converted in a non-canonical way in the language server. This PR canonicalize the URI.
> Fix status view on windows

- src/language/dafnyInstallation.ts
- src/language/dafnyToolInstaller.ts
- src/language/githubReleaseInstaller.ts
This PR adds a feedback mechanism is users using "Latest Stable" or "Latest Nightly" one day encounter a major version bump.
If so, it displays a dialog box like this:
> Prepare migration for Dafny 4

- CHANGELOG.md
- package-lock.json
- package.json
- src/constants.ts
- src/language/dafnyToolInstaller.ts
- src/language/githubReleaseInstaller.ts
- src/test/verification.test.ts
- Update version to 3.0.4
- Use Dafny 3.11
- Remove the major version upgrade checks when 'latest nightly' is used, since they would always trigger because the 'version' for nightly starts with `n` and that's never equal to the latest major version number.
- Remove `.only` from test, so the other tests run again
> Release v3.0.4 (updated Dafny to 3.11.0)

- publish_process.js
This avoids the edge case where a commit message has a semver-style version number in the message body (as is often the case in dependabot commits), which results in the publish process erroneously exiting early.
> fix: check commit msg's first line for lastPreparedTag

- README.md
- publish_process.js
- Removed a space in README.md
- `./publish_process.js` now accepts to publish a new version even if there was no added commit to the extension (e.g. to support a new version of Dafny by default)
> Support for zero-commit updates

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
This highlight adds support for detecting type annotations like `FunName<T(0,!new)>` to ensure it's a function name, not a type
Fixes #370
Proof:
> Fix: Function declarations not highlighted as types

- package.json
- src/language/api/compilationStatus.ts
- src/ui/compilationStatusView.ts
- src/ui/messages.ts
- New statuses are shown when using Dafny master
- Statuses still work as they did when using Dafny 4.0
> Support new IDE states, parsing and preparing verification

- src/ui/ghostDiagnosticsView.ts
For some reason, the IDE was ignoring ghost diagnostics if their length was empty, which can be very frequent after removing ghost code, so ghost highlighting was simply not updated. This PR removes the shortcut so that empty ghost diagnostics erase any current ghost highlighting. Fixes #372
> Fix: Empty ghost diagnostics no longer ignored

- src/ui/verificationSymbolStatusView.ts
Use a try/finally to ensure the finally code runs. If it doesn't run the whole verification as tests UI gets stuck
Manual testing for now.
> Prevent verification as tests UI from becoming unresponsive

- src/ui/compilationStatusView.ts
- src/ui/verificationGutterStatusView.ts
- src/ui/verificationSymbolStatusView.ts
- Show "preparing verification" instead of "waiting for free solver" when all verification symbols are in a queued state. This is OK for Dafny 4.2.0, since "preparing verification" could mean "waiting for free solver". For the upcoming Dafny, this situation usually happens when Dafny is performing translation to Boogie and resolution to Boogie, so the message "preparing verification" is more correct.
- Always show all known verification symbols in the test panel, instead of only those included in the current file. Together with project mode, this enables easily getting an overview of all verifiables available in the project.
- Opened a customer project. Triggered verification for everything in the project. Inspected the status bar, gutter icons and the testing panel.
> Always show all verifiable symbols in the test panels

- src/language/api/compilationStatus.ts
- src/language/dafnyLanguageClient.ts
- src/ui/compilationStatusView.ts
- src/ui/dafnyIntegration.ts
- src/ui/verificationGutterStatusView.ts
- src/ui/verificationSymbolStatusView.ts
- Let the status bar remember the message it has when resolution was previously finished, so it can show that message again when resolution finishes again. This is required to keep an up-to-date status bar together with the server changes in https://github.com/dafny-lang/dafny/pull/4523. This change is only triggered by the new event "ResolutionSucceeded", and so is backwards compatible with older Dafny versions.
- Do not let `VerificationSymbolStatusView` update the status bar, but let the status bar work independently, so the status bar remains up to date even if 'verification as tests' is turned off.
- Test that the status bar behaves well with https://github.com/dafny-lang/dafny/pull/4523 
- Test that the status bar behaves well on Dafny 4.2
- Did not manage to test against 3.7 …
> Make status bar forward compatible with upcoming Dafny release

- src/constants.ts
- src/dotnet.ts
- src/ui/messages.ts
Fixes #442.
* Relaxes the .NET runtime version check to only require the .NET Runtime (instead of ASP.NET Core too), and to permit versions later than 6.0.x.
* Make the version check error message more concise, in order to reduce the likelihood that VS Code hides the notification (due to the message being too long to fit on screen).
> fix: relax .NET runtime version check

- src/language/dafnyLanguageClient.ts
Dafny's `--plugin` argument doesn't expect an index before the path to the plugin DLL, both in terms of how plugin arguments are parsed in the Dafny code and according to the relevant [documentation](https://github.com/dafny-lang/dafny/blob/master/docs/DafnyRef/UserGuide.md#136117-plugins). Confirmed by testing with an example plugin.
> Fix plugin arguments to Dafny server

- package.json
- src/language/dafnyLanguageClient.ts
The plugins option of the IDE was no longer working because we were outputting the index. It might not matter that much now that we have project files, but it's now fixed and I also deprecated the options to add plugins this way since regular options work as much as project files.
Fixes https://github.com/dafny-lang/dafny/issues/4759
I did not bother writing tests because it's a deprecated option anyway.
> Fix: Dafny plugins working again.

- CHANGELOG.md
- package-lock.json
- package.json
- src/constants.ts
(Follows usual process, see e.g. PR for 4.4.0: https://github.com/dafny-lang/ide-vscode/pull/457)
> Release v3.2.3 (updated Dafny to 4.5.0)

- README.md
- package.json
Fixes #422
- Update the description of `dafny.version`
- Remove outdated descriptions of options in the README
- Manually inspected the new description
> Update the description of dafny.version

- src/extension.ts
This change would export the `ExtensionRuntime` object that is created such that other extensions can access it.
This would, for example, allow other extensions to depend on this extension and use the `LanguageClient` it creates to send requests without the need to start their own `LanguageClient`.
With the current changes other extensions could access the `LanguageClient` like this:
```typescript
const client: LanguageClient = vscode.extensions.getExtension('dafny-lang.ide-vscode')?.exports.client;
client.sendRequest(...)
```
Note: Perhaps if exporting `ExtensionRuntime` is a bit too broad, only the `LanguageClient` could be exported instead.
> Export ExtensionRuntime (or LanguageClient) for other extensions

- .github/workflows/ci.yaml
Publish the Dafny VScode extension to OpenVSX (https://open-vsx.org/) as well.
> Add script for publishing to OpenVsx

- src/language/customPathInstaller.ts
When you set a custom path for the CLI through `dafny.cliPath`, and set `dafny.version` to `custom`, in theory, the extension should copy all relevant DLL and executable files in the `dafny.cliPath` to a tmp dir, which is then used to launch the language server.
This is implemented by iterating over all files in the directory of the configured path, and copying only the ones which match a given filter: names ending with `.dll`, `.exe`, etc.
On Linux, executables usually won't have those file extensions, and thus, the file the user configured path points to might end up not being copied.
This leads to language server failing because it can't find the file specified in `dafny.cliPath`.
This PR simply changes the filter so that the file pointed to always passes the filter, so that it always …
> Fix binary copying to temporary folder on custom path

- src/test/highlight/regression-highlight.dfy
- syntaxes/Dafny.tmLanguage
Before:
After:
Related issue
https://github.com/dafny-lang/dafny/issues/5795
@-attributes are now ready on Dafny, and they also have auto-complete from the language server. Having syntax hightlight will make them shine.
I added a "visual regression test". It's unfortunate that they are not programmatically tested, but I hope that we will have semantic highlighting that will get rid of that issue.
> Support for @-syntax for attributes

- src/language/dafnyToolInstaller.ts
- src/language/githubReleaseInstaller.ts
Fixes https://github.com/dafny-lang/ide-vscode/issues/515
When using latest-nightly, enable starting using a cached nigthly when there is no internet connection
> Enable starting using a cached nigthly

- CONTRIBUTING.md
I added instructions in the `CONTRIBUTING.md` about how to view the trace, as I needed this recently, so I know that the steps are correct.
> Chore: added instructions on how to view the trace

- src/language/customPathInstaller.ts
When using a custom Dafny installation, this extension copies it to a temp directory. However, the `mkdtemp` call has a typo where it uses `vscode-dafny-dlls-'` instead of `path.join(os.tmpdir(), 'vscode-dafny-dlls-')`, which causes the temp directory to appear in VSCode's cwd (in my case $HOME). This PR fixes that.
https://nodejs.org/api/fs.html#fspromisesmkdtempprefix-options also has an example of how to correctly use `mkdtemp`.
> Call fs.promises.mkdtemp on the correct path to prevent making a temp dir in $HOME

- src/language/customPathInstaller.ts
Builds of Dafny downloaded from the [GitHub Releases page](https://github.com/dafny-lang/dafny/releases) include all necessary support libraries, so they don't depend on an external .NET runtime. When we copy a custom dafny to a tmpdir, we need to copy these libraries too, or the language server will fail to start.
Windows libraries, being `.dll`s, were probably already copied, but on macOS and Linux, shared libraries end in `.dylib` and `.so`, respectively.
> Also copy native libraries when copying a custom dafny to tmpdir

- package.json
- src/constants.ts
Fixes #219
- Rename "Language Server Launch Args" to "Dafny Server Arguments"
- Rename "Run Args" to "Dafny Run Arguments"
Note: this PR makes all currently configured values for these options be lost, so let's make sure we only have to change the name once.
New look:
> Update option names

- publish_process.js
This PR fixes an issue in the publish process where systems without `xdg-open` would fail when trying to automatically open the changelog file.
- Modified `getCommandLine()` to return empty string for unknown platforms instead of 'xdg-open'
- Provides user guidance when automatic file opening is not available
- Tested on a Linux cloud desktop without xdg-open installed
- Was used to release 3.5.0, needed for 3.5.1
> Fix publish process for Linux systems without xdg-open

- src/language/githubReleaseInstaller.ts
Users on x86_64 Macs are getting "incompatible architecture" errors because the extension downloads arm64 Dafny releases instead of x64 releases. This happens when VS Code runs under Rosetta or as a Universal Binary, causing `os.arch()` to return incorrect architecture information.
Use `uname -m` system command on macOS to get actual hardware architecture instead of relying on Node.js process architecture. Maps `x86_64` → `x64` and `arm64` → `arm64` for correct release downloads. Includes fallback to `os.arch()` if system command fails.
Only affects macOS - other platforms continue using existing logic.
Fixes the issue where extension downloads wrong architecture on macOS.
> Fix macOS architecture detection for Dafny downloads
